import Image from "next/image";
import { ArrowRight, Leaf, MapPin, Sprout, Mail } from "lucide-react";
import SiteHeader from "@/components/site-header";
import InquiryForm from "@/components/inquiry-form";
import { products, faq } from "@/lib/content";

const process=[["01","Grow","Cacao begins in healthy soil, grown with care for biodiversity and responsible farm practices."],["02","Ferment","Careful post-harvest fermentation develops the natural character of each cacao lot."],["03","Craft","Beans are roasted, refined and transformed in small batches into expressive chocolate."],["04","Share","Thoughtfully made bars and tablea bring Philippine cacao from our farm to your table."]];

export default function Home(){return <>
<a href="#main" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[60] focus:rounded-lg focus:bg-gold focus:px-4 focus:py-3">Skip to content</a>
<SiteHeader/>
<main id="main">
<section className="hero relative overflow-hidden bg-cocoa text-parchment"><Image src="/images/cacao-beans-header.jpg" alt="Cacao beans from DADs Farm in Capiz" fill priority sizes="100vw" className="object-cover opacity-55"/><div className="hero-overlay absolute inset-0"/><div className="container relative grid min-h-[760px] items-end py-20 lg:grid-cols-[1.1fr_.9fr] lg:gap-20"><div className="max-w-3xl"><p className="eyebrow !text-gold">From healthy soil to exceptional chocolate</p><h1 className="display mt-5 text-5xl leading-[.94] md:text-7xl">Chocolate rooted in the land of Capiz.</h1><p className="mt-7 max-w-2xl text-base leading-8 text-parchment/80 md:text-lg">OGUIA Chocolates by DADs Farm creates bean-to-bar chocolate from cacao grown with care in Old Guia, Ma-ayon, Capiz—where the health of the soil becomes the quality of every bite.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#chocolates" className="btn-primary">Explore our chocolate <ArrowRight size={17}/></a><a href="#story" className="btn-secondary">Our story</a></div><div className="mt-12 grid max-w-2xl gap-5 sm:grid-cols-3">{["Farm connected","Bean-to-bar","Made in Capiz"].map(x=><div key={x} className="border-t border-gold/70 pt-3 text-sm font-bold">{x}</div>)}</div></div><div className="glass-card hidden lg:block"><p className="eyebrow !text-gold">The DADs Farm vision</p><p className="display mt-4 text-3xl leading-tight">“An ecologically sustainable, diversified farm that champions healthy, naturally grown and affordable farm-to-table produce, while elevating OGUIA Chocolates and artisanal tablea into world-renowned symbols of Philippine cacao.”</p><div className="gold-rule my-6"/><p className="text-sm leading-7 text-parchment/70">From sustainable farming to exceptional cacao craftsmanship, DADs Farm connects the health of the land with the quality, accessibility and global identity of Philippine cacao.</p></div></div></section>

<section id="story" className="section"><div className="container grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div className="relative min-h-[520px] overflow-hidden rounded-[28px]"><Image src="/images/cacao-background.jpg" alt="Cacao farm and beans representing DADs Farm's origin" fill sizes="(max-width:1024px) 100vw,45vw" className="object-cover"/></div><div><p className="eyebrow">Our origin</p><h2 className="display mt-4 text-4xl leading-tight md:text-5xl">A family farm. A Philippine chocolate story.</h2><p className="mt-6 text-base leading-8 text-cocoa/70">DADs Farm, named after the family names Dariagan, Arbolida, and Depon, is the realization of the shared dream of spouses Emilyn D. Arbolida-Depon and Jose Roy D. Depon. What began in 2017 as an idle piece of land in Barangay Old Guia, Ma-ayon, Capiz, was gradually transformed into a thriving cacao farm. Today, cacao trees grow alongside fruit-bearing and native trees, creating a diverse farm ecosystem that promotes both sustainability and productivity.</p><p className="mt-5 text-base leading-8 text-cocoa/70">In 2020, during the COVID-19 pandemic, Roy made the bold decision to leave his career as a seafarer and dedicate himself full-time to chocolate making and the development of their farm. Through hard work, innovation, and support from the DOST SETUP Program, he developed premium tablea and artisanal chocolates that soon gained recognition in Capiz and beyond.</p><p className="mt-5 text-base leading-8 text-cocoa/70">His dedication and craftsmanship received national recognition when his Flavored Tablea was awarded 3rd Runner-Up at the 2024 Cacao Congress in Cebu City.</p><p className="mt-5 text-base leading-8 text-cocoa/70">Inspired by the success of their farm and their deep connection to their community, the couple created O'Guia Chocolates, named after their home community of Barangay Old Guia, Ma-ayon, Capiz.</p><p className="mt-5 text-base leading-8 text-cocoa/70">Today, O'Guia Chocolates proudly produces high-quality chocolate made from locally grown cacao—bringing together great taste, sustainable farming, Filipino craftsmanship, and the rich story of our community in every product.</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="card p-5"><Sprout className="text-gold"/><h3 className="display mt-5 text-xl">Farm connected</h3><p className="mt-2 text-sm leading-6 text-cocoa/60">Origin and craft stay closely connected.</p></div><div className="card p-5"><Leaf className="text-gold"/><h3 className="display mt-5 text-xl">Regenerative mindset</h3><p className="mt-2 text-sm leading-6 text-cocoa/60">Biodiversity and soil health guide the farm journey.</p></div></div></div></div></section>

<section id="chocolates" className="section bg-cream"><div className="container"><div className="max-w-2xl"><p className="eyebrow">Our chocolate</p><h2 className="display mt-4 text-4xl md:text-5xl">Made for people who taste the difference.</h2><p className="mt-5 text-sm leading-7 text-cocoa/65">Explore our growing collection of bean-to-bar chocolate and tablea, made with a focus on cacao character rather than excessive sweetness.</p></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.map(([name,description],i)=><article key={name} className="product-card"><div className="product-art"><span>OGUIA</span><small>{String(i+1).padStart(2,"0")}</small></div><div className="p-6"><p className="eyebrow">Chocolate collection</p><h3 className="display mt-3 text-2xl">{name}</h3><p className="mt-3 text-sm leading-6 text-cocoa/60">{description}</p><a href="#contact" className="mt-6 inline-flex items-center gap-2 text-sm font-extrabold text-canopy">Ask about this <ArrowRight size={15}/></a></div></article>)}</div></div></section>

<section id="process" className="section"><div className="container"><div className="grid gap-10 lg:grid-cols-[.65fr_1.35fr]"><div><p className="eyebrow">From farm to bar</p><h2 className="display mt-4 text-4xl md:text-5xl">Every handoff matters.</h2></div><div className="grid gap-4 sm:grid-cols-2">{process.map(([num,title,copy])=><article className="card p-6" key={num}><span className="num text-gold">{num}</span><h3 className="display mt-8 text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-cocoa/60">{copy}</p></article>)}</div></div></div></section>

<section id="values" className="bg-canopy py-24 text-parchment"><div className="container grid gap-12 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow !text-gold">Why OGUIA</p><h2 className="display mt-4 text-4xl md:text-5xl">Taste with a sense of place.</h2><p className="mt-6 max-w-xl text-base leading-8 text-parchment/70">We are building a chocolate brand that connects flavour, farming and Filipino identity. The goal is not simply to make another chocolate bar—it is to create a product people can trace back to a living place.</p></div><div className="grid gap-4 sm:grid-cols-2">{[["Origin","Cacao connected to Old Guia, Ma-ayon, Capiz."],["Craft","Small-batch chocolate making with attention to cacao character."],["Sustainability","Regenerative, community-centered farming ambitions."],["Culture","A Philippine point of view expressed through ingredients, stories and design."]].map(([title,copy])=><div className="border-t border-gold/60 pt-5" key={title}><h3 className="display text-2xl text-gold">{title}</h3><p className="mt-2 text-sm leading-6 text-parchment/65">{copy}</p></div>)}</div></div></section>

<section className="section"><div className="container rounded-[28px] bg-cream p-8 md:p-12"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="eyebrow">More than chocolate</p><h2 className="display mt-4 text-4xl">A farm-to-table ecosystem.</h2><p className="mt-5 text-sm leading-7 text-cocoa/65">DADs Farm also develops products from local farm ingredients, creating opportunities to reduce waste, support local livelihoods and keep more value close to the source.</p></div><div className="grid grid-cols-2 gap-3 text-sm font-bold sm:grid-cols-4">{["Cacao","Sugarcane","Fruit","Local crops"].map(x=><div key={x} className="rounded-xl border border-[#dfd4bd] bg-parchment p-5 text-center">{x}</div>)}</div></div></div></section>

<section id="faq" className="section bg-cream"><div className="container grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Questions</p><h2 className="display mt-4 text-4xl">Good questions deserve clear answers.</h2></div><div className="divide-y divide-[#d9cdb7]">{faq.map(([q,a])=><details className="group py-5" key={q}><summary className="flex cursor-pointer list-none justify-between gap-4 font-bold">{q}<span className="text-gold group-open:rotate-45">+</span></summary><p className="max-w-2xl pt-4 text-sm leading-7 text-cocoa/65">{a}</p></details>)}</div></div></section>

<section id="contact" className="section bg-cocoa text-parchment"><div className="container grid gap-12 lg:grid-cols-2"><div><p className="eyebrow !text-gold">Visit, taste, connect</p><h2 className="display mt-4 text-4xl md:text-5xl">Bring OGUIA to your table.</h2><p className="mt-6 max-w-md text-sm leading-7 text-parchment/70">For product inquiries, wholesale, gifting, hospitality partnerships or farm-to-bar conversations, reach the DADs Farm team.</p><div className="mt-8 grid gap-4 text-sm"><a href="mailto:dadscacaofarm@gmail.com" className="flex items-center gap-3"><Mail size={18} className="text-gold"/>dadscacaofarm@gmail.com</a><p className="flex items-center gap-3"><MapPin size={18} className="text-gold"/>Brgy. Old Guia, Ma-ayon, Capiz, Philippines</p></div></div><div className="rounded-2xl bg-parchment p-6 text-cocoa md:p-8"><InquiryForm/></div></div></section>
</main><footer className="bg-cocoa pb-8 text-parchment/50"><div className="container border-t border-[#654b40] pt-7 text-xs">© {new Date().getFullYear()} OGUIA Chocolates by DADs Farm · Old Guia, Ma-ayon, Capiz, Philippines</div></footer></>}